### Listar todos os clientes
GET http://localhost:3000/api/clientes

###

### Buscar cliente por ID
GET http://localhost:3000/api/clientes/1

###

### Cadastrar cliente
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
    "nome": "ls",
    "email": "losoco@gmail.com",
    "telefone": "489974998"
}

###
DELETE http://localhost:3000/api/clientes/4

###
PUT http://localhost:3000/api/clientes/1
Content-Type: application/json

{
    "nome": "Lorenzo Atualizado",
    "email": "lorenzo@gmail.com",
    "telefone": "48988888888"
}